### ISSUE TITLE
Task: Start Fish Design

### ISSUE THREAD

**Issue by isabela-souzahara** [PhilipC6/Kujira-ISP#13]
creating the design of the fish so that it can be appealing to look at when playing the kujira game Working on #12

**Comment by NimetaZ** [comment]
Nearly done, I just need to commit from my home computer.

**Comment by NimetaZ** [comment]
Need to commit, I keep forgetting

**Comment by isabela-souzahara** [comment]
Most fish are complete, only missing humpback whale
