### ISSUE TITLE
Task: Sizing of Fish (Betta Fish Through Salmon)

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#20]
Creating sizing of the fish so that they are not all the same and all of the group member will be able to have access of the right fish size linked to story #12

**Comment by isabela-souzahara** [comment]
[Document](https://github.com/PhilipC6/Kujira-ISP/blob/main/UI%20&%20UX%20Design/Godot%20Fish%20Size.md)
