### ISSUE TITLE
Task: Over the line loss condition

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#23]
When the fishes get to the top of the open box for more than five seconds the game will be over.
Linked to #1

**Comment by isabela-souzahara** [comment]
Added a 5-second timer to signal loss when fish remains above loss line. Files in the Loss Condition folder inside the Godot project are related to this task.
[Project File](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/LossCondition.zip)
