### ISSUE TITLE
Task: combining background project file with the the combined test project file

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#42]
making sure that one fish is not behind the background. Linked to #12

**Comment by isabela-souzahara** [comment]
Adjusted background and code to ensure that fish correctly spawned on top of the background in the Combined Test file. Still need to adjust buttons to make them work properly.
[Project File](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Combined%20Test%20with%20Background.zip)
