### ISSUE TITLE
Task: combining all the files

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#45]
combining all of the files into a large one

**Comment by isabela-souzahara** [comment]
Added [Weighted Generation](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Weighted%20Generation.zip), [Main Menu and Restart Button](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Main%20Menu%20Buttons%20Revised.zip), and [Fish Collision Shapes](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/kujira.zip) to [Combined Test](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Combined%20Test%20with%20Background.zip).
Restart Button still does not function correctly.
[Project File](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Combined%20Test%202.0.zip)
