### ISSUE TITLE
Task: Score

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#46]
make score increase every time certain fishes combine #3

**Comment by isabela-souzahara** [comment]
Reminder: completed up to Blobfish Merge

**Comment by isabela-souzahara** [comment]
Added score for the entire merge sequence and added score in the restart function.

[Project File](https://github.com/PhilipC6/Kujira-ISP/blob/Development/Source%20Code/Score.zip)
