### ISSUE TITLE
Task: Create an image of the fishes in ascending order

### ISSUE THREAD

**Issue by Anjie-o** [PhilipC6/Kujira-ISP#55]
Create an image of the fishes in ascending order, and put it on the main menu screen or game screen, so that the player is aware of what the next fish is when two fishes are merged. Working on #1 Summer's Story

**Comment by isaaclee467** [comment]
Created a list of the Kujira fish from smallest to biggest so that the player knows which ones are created when merged. Closing Task #55.

**Comment by isaaclee467** [comment]
Created a list of the Kujira fish from smallest to biggest so that the player knows which ones are created when merged. Closing Task #55
